export const testData = [
  { 
    id: 2,
    firstName: 'Emil',
    lastName: 'Kulmuhametov',
    jobTitle: 'HOJSD',
    email: 'emilkul@gmail.com',
    emailAddress:'https://mail.google.com/',
    address: 'Kooperativnaya 6a',
    age: 23,
    role: ['ADMIN', 'USER', 'HEAD_OF_THE_DEPARTMENT'],
    withHoldingTax: 0.5,
    salary: 750,
    country: 'UA',
    city: 'Kharkiv',
    socialProfileLink: 'https://vk.com/id170185455',
    cardNumber: 1232123412447722,
  },
  { 
    id: 1,
    firstName: 'Vadik',
    lastName: 'Trotsenko',
    jobTitle: 'Developer JS',
    email: 'trocenkovadik@gmail.com',
    emailAddress:'https://mail.google.com/',
    address: 'Svobody 11',
    age: 22,
    role: ['USER'],
    withHoldingTax: 0.5,
    salary: 400,
    country: 'UA',
    city: 'Rubezhnoe',
    socialProfileLink: 'https://vk.com/vadiktrocenko',
    cardNumber: 1232123412447722,
  },
  { 
    id: 3,
    firstName: 'Oleg',
    lastName: 'Ivanov',
    jobTitle: 'Developer JS',
    email: 'trocenkovadik@gmail.com',
    emailAddress:'https://mail.google.com/',
    address: 'Svobody 11',
    age: 22,
    role: ['USER', 'ADMIN'],
    withHoldingTax: 0.5,
    salary: 400,
    country: 'UA',
    city: 'Rubezhnoe',
    socialProfileLink: 'https://vk.com/vadiktrocenko',
    cardNumber: 1232123412447722,
  },
  { 
    id: 4,
    firstName: 'Maksim',
    lastName: 'Sidorov',
    jobTitle: 'Developer JS',
    email: 'trocenkovadik@gmail.com',
    emailAddress:'https://mail.google.com/',
    address: 'Svobody 11',
    age: 22,
    role: ['USER', 'ADMIN'],
    withHoldingTax: 0.5,
    salary: 400,
    country: 'UA',
    city: 'Rubezhnoe',
    socialProfileLink: 'https://vk.com/vadiktrocenko',
    cardNumber: 1232123412447722,
  },
  { 
    id: 5,
    firstName: 'Kolya',
    lastName: 'Petrov',
    jobTitle: 'Developer JS',
    email: 'trocenkovadik@gmail.com',
    emailAddress:'https://mail.google.com/',
    address: 'Svobody 11',
    age: 22,
    role: ['USER', 'ADMIN'],
    withHoldingTax: 0.5,
    salary: 400,
    country: 'UA',
    city: 'Rubezhnoe',
    socialProfileLink: 'https://vk.com/vadiktrocenko',
    cardNumber: 1232123412447722,
  },
  { 
    id: 5534343,
    firstName: 'Kolya',
    lastName: 'Petrov',
    jobTitle: 'Developer JS',
    email: 'trocenkovadik@gmail.com',
    emailAddress:'https://mail.google.com/',
    address: 'Svobody 11',
    age: 22,
    role: ['USER', 'ADMIN'],
    withHoldingTax: 0.5,
    salary: 400,
    country: 'UA',
    city: 'Rubezhnoe',
    socialProfileLink: 'https://vk.com/vadiktrocenko',
    cardNumber: 1232123412447722,
  },
]