export const testData = [
  { 
    firstName: 'Vadik',
    lastName: 'Trotsenko',
    email: 'vadik@mail.com',
    address: 'Svobody 11',
    age: 22,
    role: ['USER'],
    withHoldingTax: 0.5,
    salary: 400,
    country: 'UA',
    city: 'Rubezhnoe',
    socialProfileLink: 'https://vk.com/vadiktrocenko',
    cardNumber: 1232123412447722,
  },
  { 
    firstName: 'Emil',
    lastName: 'Kulmuhametov',
    email: 'emilkul@gmail.com',
    address: 'Kooperativnaya 6a',
    age: 23,
    role: ['ADMIN'],
    withHoldingTax: 0.5,
    salary: 750,
    country: 'UA',
    city: 'Kharkiv',
    socialProfileLink: 'https://vk.com/vadiktrocenko',
    cardNumber: 1232123412447722,
  }
]