export const CREATE_PAYEE = 'CREATE_PAYEE';
export const DELETE_PAYEE = 'DELETE_PAYEE';
export const ACTIVE_PAYEE = 'ACTIVE_PAYEE';
export const DEACTIVATE_PAYEE = 'DEACTIVATE_PAYEE';
export const PAY_PAYEE = 'PAY_PAYEE';
export const UPDATE_PAYEE = 'UPDATE_PAYEE';
export const GET_PAYEES_SUCCESS = 'GET_PAYEES_SUCCESS';
export const GET_PAYEE_PROFILE_SUCCESS = 'GET_PAYEE_PROFILE_SUCCESS';
