export const CREATE_PAYEE = 'CREATE_PAYEE';
export const DELETE_PAYEE = 'DELETE_PAYEE';
export const ACTIVE_PAYEE = 'ACTIVE_PAYEE';
export const DEACTIVATE_PAYEE = 'DEACTIVATE_PAYEE';
export const PAY_PAYEE = 'PAY_PAYEE';
